### ISSUE TITLE
Line break rendering

### ISSUE THREAD

**Issue by apstanley** [levito/tt-rss-feedly-theme#116]
Hi there. Long time user. I recently updated TT-RSS and the Feedly theme. I've noticed a problem and I don't have the CSS skills to fix myself. I think there's a problem with line break "<br>" but I'm not 100% sure. If I look at how this theme renders an entry vs the default, there's quite a difference. But this doesn't happen for all entry, however, for example, within http://bt.etree.org/rss/bt_etree_org.rdf you notice how unreadable it is with the Feedly theme.  The previous version I used, which was from a couple of years ago, didn't have this problem. Can you see what's wrong or contact me? Thanks.

![Screenshot 2023-03-27 151148](https://user-images.githubusercontent.com/12999683/228056925-460cd952-a194-45fb-a88a-6c54a77b5f7a.png)

![Screenshot 2023-03-27 151251](https://user-images.githubusercontent.com/12999683/228056944-eb57785a-4609-4403-8be8-cf9803e3267e.png)

**Comment by levito** [comment]
Hey @apstanley, really good catch, thanks a lot for submitting this, and for providing the feed so I could check what was happening. Should be fixed now, can you please update and check if it's good now?

**Comment by levito** [comment]
Thanks for checking again! This should now also be fixed. It was indeed a Firefox-only thing.

If you're interested in what caused it: I recently switched to spacing out the content with the [lobotomized owl method](http://alistapart.com/article/axiomatic-css-and-lobotomized-owls/). This makes many things easier and helps with consistent spacing, but apparently it has its own issues. Firefox was also adding a margin-top to any `br` that came after any other tag, so I had to explicitly remove it. Chrome doesn't do this.

The original issue with all the line-breaks being removed was caused by me trying to prevent multiple `br`s in a row (like `Something<br><br><br><br>and more`) creating huge gaps with something like `br + br { display: none }`. But with HTML like `Line 1<br>Line 2<br>Line 3`, the second `br` is also matched by `br + br`, which I didn't consider.
