### ISSUE TITLE
Applying the theme leads to a broken interface.

### ISSUE THREAD

**Issue by VlaK0r** [levito/tt-rss-feedly-theme#119]
Hello friends!
Please tell me what it could be because of?

![image](https://github.com/levito/tt-rss-feedly-theme/assets/77666575/26738d61-54d1-4379-bed1-7c987f41795b)

**Comment by levito** [comment]
Hey @VlaK0r, the theme worked for you a couple of days ago, right? What did you do before it stopped working? And did you try a different theme to see if that's working?

**Comment by VlaK0r** [comment]
> Hey @VlaK0r, the theme worked for you a couple of days ago, right? What did you do before it stopped working? And did you try a different theme to see if that's working?

I have reassembled the docker image for raspberry pi 4. For arm platform. And now I don't understand why all third-party themes don't work properly. 
I turned to you, because I think you understand this issue better than anyone.

**Comment by levito** [comment]
Sorry, I can't help you with that. Maybe this helps: https://tt-rss.org/wiki/FAQ#ui-is-missing-css-or-is-otherwise-visibly-broken

I'll close this issue since it's not related to this theme.

**Comment by whatfuturedotlol** [comment]
hi, i just installed this theme and i am having the same issue. this is the first time i've installed it and so it was never working.

installed via docker

Linux tt-rss 4.4.302+ #69057 SMP Sat Sep 23 21:44:10 CST 2023 x86_64 
Linux build-3-18-x86_64 5.15.108-0-lts #1-Alpine SMP Fri, 21 Apr 2023 05:55:14 +0000 x86_64 Linux 

i cloned the dist repo and copied it into themes.local, i find the themes listed in the preferences. i select any of the feedly ones and they all break in the same way. normal themes work fine.

am on firefox 120.0.1 (64-bit)

let me know if you need other info
![Screenshot 2023-12-16 at 21 11 54](https://github.com/levito/tt-rss-feedly-theme/assets/129675251/efc9c890-bbea-4c01-af20-80695ebc347c)

**Comment by ourovoros** [comment]
I was in the same situation. After checking, it seems that the current MASTER branch does not contain the necessary files.

Please specify the branch and clone the GIT repository.
$ git clone **-b dist** https://github.com/levito/tt-rss-feedly-theme.git

Then, go to the cloned directory and
$ cd tt-rss-feedly-theme
Copy the entire contents of the directory to the themes.local folder.
Adjust the volume name(tt-rss_web-nginx_1 is my environment) to suit your environment.
$ sudo docker cp ./ tt-rss_web-nginx_1:/var/www/html/tt-rss/themes.local/

As of 5/20/2024, the following files are present and
it works fine when I try it.
$ sudo docker exec tt-rss_web-nginx_1 ls /var/www/html/tt-rss/themes.local/
feedly/
feedly-high-contrast.css
feedly-high-contrast_auto.css
feedly-high-contrast_night.css
feedly-sepia-contrast.css
feedly-sepia-contrast_auto.css
feedly-sepia-contrast_night.css
feedly-sepia.css
feedly-sepia_auto.css
feedly-sepia_night.css
feedly.css
feedly_auto.css
feedly_night.css
local-overrides.css
local-overrides.js

Good luck!

**Comment by smikwily** [comment]
I was all excited about your update on this, but it still isn't working for me. Are you guys working off of the official docker or one of the others out there? I could always get these working on other variations, but since I've moved to the official docker, I've had no luck.

**Comment by ourovoros** [comment]
Hi @smikwily,

Hmmm, strange.

I am using the official Docker image. I have Git clone from the following URL
https://gitlab.tt-rss.org/tt-rss/tt-rss

However, It seems docker-compose.yml included in Git is not configured enough.
In particular, there is no setting to make it persistent, so the contents will disappear when Docker is down.
I replaced it with docker-compose.yml in the official Q&A and Docker Installation Guide. See the following URL
This is different from the one included in Git.
https://tt-rss.org/wiki/InstallationNotes

I'm not too familiar with Dokcer, but maybe without below, can't make it persistent and may not have a place to copy the theme to.
volumes:.
  db:.
  app:.
  backups:

I then copied the theme to the Docker volume I built.
I hope it works.

**Comment by smikwily** [comment]
Thanks for the response, @ourovoros . When I configured mine, I tried to stick to the "official way" of doing thing, so I wouldn't break things in the future, etc. The docs specifically mention instructions on how to get plugins and themes working persistently here: https://tt-rss.org/wiki/InstallationNotes#how-do-i-add-plugins-and-themes

I used that and I can see the themes listed, but as soon as I choose one of them, that's when things blow up.

**Comment by ourovoros** [comment]
Ah, so you chose to mount the file instead of copying it directly to the volume. I'm lazy, so I ended up overwriting the file directly.

I saw the URL you posted. I tried this method.
https://tt-rss.org/wiki/InstallationNotes#how-do-i-add-plugins-and-themes

This overwrites the Docker Volume with the local folder on the host side, but have you changed the settings or configuration of the files in the local folder on the host side?

When I tried it, a lot of things fell apart, so I added only theme.local and plugin.local, which I think need to be updated, to overwrite the Docker Volume with the local folder. At that time, as far as I can see from the configuration file, app and nginx are exchanging data, so I think it won't work properly unless you add both app and nginx.

Specifically, I made the following modifications.
**docker-compose.yml**
  **app:**
    image: cthulhoo/ttrss-fpm-pgsql-static:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
      - ./themes.local:/var/www/html/tt-rss/themes.local **<-- added**
      - ./plugins.local:/var/www/html/tt-rss/plugins.local **<-- added**
and........
  **web-nginx:**
    image: cthulhoo/ttrss-web-nginx:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - app:/var/www/html:ro
      - ./themes.local:/var/www/html/tt-rss/themes.local **<-- added**
      - ./plugins.local:/var/www/html/tt-rss/plugins.local **<-- added**

Of course, store CSS and Plugins in themes.local in the host's local folder.
Also, if possible, it is better to try it after deleting Volume and Container.
You can download RSS and configuration files from OPML in Preferences, so save them in advance.

After starting Docker, check the results with
$ sudo docker exec tt-rss_app_1 ls /var/www/html/tt-rss/themes.local
and
$ sudo docker exec tt-rss_web-nginx_1 ls /var/www/html/tt-rss/themes.local

If the contents of your local folder are updated with the Docker container folder, everything is fine. If either one is empty, it will not work as expected. Please adjust the path settings etc. to suit your environment.

I have attached images for your reference.
![01](https://github.com/levito/tt-rss-feedly-theme/assets/4804527/4e6db23a-da5c-4409-bd7b-8e85f462a733)
![02](https://github.com/levito/tt-rss-feedly-theme/assets/4804527/9f3727db-2ffd-4361-b58c-2f0da62558e7)
![03](https://github.com/levito/tt-rss-feedly-theme/assets/4804527/06e379ae-06f7-4e10-8d69-f6c7e89fa6ca)
![04](https://github.com/levito/tt-rss-feedly-theme/assets/4804527/637915b2-c3dc-40d6-a5f0-570e2cf0122a)

**Comment by smikwily** [comment]
Thank you for your response, @ourovoros. I probably should have led with the fact that I was trying to run this on Unraid using the Docker Compose Manager, but I wasn't terribly comfortable with the whole thing anyhow and wasn't sure if that was going to factor in or not, so I wanted to do a little more checking on my own.

I did end up getting it to work by changing the info provided in the Installation Guide entry for 
[How do I add plugins and themes?](https://tt-rss.org/wiki/InstallationNotes#how-do-i-add-plugins-and-themes)

Instead of using the officially recommended route of changing:

```
volumes:
      - app:/var/www/html
```

To:

```
volumes:
      - /opt/tt-rss:/var/www/html
```

I instead used the more "Unraid friendly":

```
volumes:
      - /mnt/user/appdata:/var/www/html
```

Once I got things up and running and put the files in that location, everything is working as I had hoped it would for both plugins.local and themes.local. I also commented back out a few overrides I had "enabled" without really understanding what they did. Anyhow, that combination got it working for me.

Thanks again for taking the time to throw your suggestions my way. It was greatly appreciated!
