### ISSUE TITLE
New tt-rss version breaks theme

### ISSUE THREAD

**Issue by Lukas0907** [levito/tt-rss-feedly-theme#25]
Hi,

this commit in tt-rss https://tt-rss.org/gitlab/fox/tt-rss/commit/393fc7d6b5e634c9618dac415252eaf40939cf31 breaks the feedly theme since it has a hard coded supported version in the beginning (which is obviously older than 16.1).

I changed it manually to 16.1 and it seems to work.

Cheers,

Lukas

**Comment by McBochi** [comment]
Changing the first line of feedly.css to 16.1 indeed works, nothing broken at first glance.
I checked however a few commits since the last update of this repository and it seems as if there are some new CSS IDs and classes that one would have to take a further look into.

@Lukas0907 you could do a quick pull request for this minor change and maybe I'll find the time to check a bit more later on.

**Comment by ardichoke** [comment]
Pull request submitted.

**Comment by levito** [comment]
Fixed with PR #26

**Comment by x86dev** [comment]
Thanks for fixing this so quickly! Greetings from Berlin!
