### ISSUE TITLE
[Request] Possible to make it Responsive ?

### ISSUE THREAD

**Issue by ekianjo** [levito/tt-rss-feedly-theme#34]
This is a great and beautiful theme - however I would like to know if it can be made to work on mobiles too (smartphones) since right now the current settings are not optimal for displays on such screens.

**Comment by smartshogu** [comment]
Just mention, there are 2 great apps available f.e. in playstore that work well on phone and tablet.

**Comment by ekianjo** [comment]
which apps do you recommend ?


On Friday, January 6, 2017, smartshogu <notifications@github.com> wrote:
> Just mention, there are 2 great apps available f.e. in playstore that
work well on phone and tablet.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/SX51gQNTbc7JFwbLiTpgHG_Bd7R7fb0xhGVj7nFFhJAXaK6iMhfaFexBA_cCH3je6wgPBuO0TK8NUWmEuDF4gaB_3gBvROYyzvfWPPRiGlAqYfdo4ekln6UUJhakugw73w1_4aPY9PqjC4siMwaWLQHFBscwwQ=s0-d-e1-ft#https://github.com/notifications/beacon/ACWMmPnj_QCbnWw8PCLMyeChtxC8rLiPks5rPfwWgaJpZM4LcgEc.gif
>

-- 
Raphael

**Comment by smartshogu** [comment]
they are called ttrss. the pay app from andrew dolgov is the best. have fun.

**Comment by levito** [comment]
Hi @ekianjo, unfortunately it's not so easy as it should be. It's because Tiny Tiny RSS uses Dojo for the UI. Dojo does all the layout stuff, so it's hard to override with a theme. Also, Dojo widgets are not very touch-friendly and can't be replaced with a theme.

I personally use News+, with a Tiny Tiny RSS plugin:
https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus
https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus.extension.ttrss

It hasn't been updated for a while but still works well for me.

**Comment by ardichoke** [comment]
I'd avoid recommending News+... it is abandonware and has some big bugs (including ones that specifically hamper TT-RSS functionality, even with the ttrss plugin). I found it totally unreliable when it came to syncing because of some of these bugs.

**Comment by levito** [comment]
I just tested a few apps and I agree, the official app seems to be the best option right now.
