### ISSUE TITLE
Width of text in blockquotes is not limited

### ISSUE THREAD

**Issue by michaelmattig** [levito/tt-rss-feedly-theme#40]
I noticed if a feed entry contains a blockquote with text in it without enclosing paragraph element, the width of the text ist not capped, rather it uses the full width of the browser.

e.g.
```
<blockquote>
Some long text
</blockquote>
```
Takes the whole width, while
```
<blockquote>
<p>Some long text</p>
</blockquote>
```
works like intended. As far as I see it, only strict XHTML requires that a blockquote only contains blocks. Thus my first example should be valid html and it should be formatted correctly.

**Comment by levito** [comment]
Hi @michaelmattig, I can't reproduce your issue, but I can imagine what you're seeing:

I limited the maximum width of paragraphs to 45em for better readability. blockquotes are not limited in width. Both is intended, because a blockquote might also contain code, which should not wrap early.

So text without paragraphs in a blockquote fills the whole width of the blockquote. But it won't scroll horizontally.

Can you confirm this behaviour?

If it's different/broken for you, what browser/version and which OS are you using?

**Comment by michaelmattig** [comment]
Yes, I can confirm this behavior. If this is intended I'm going to have to live with it (or fork). Thanks for your response, though.
