### ISSUE TITLE
Last three characters cut off from title

### ISSUE THREAD

**Issue by Unending** [levito/tt-rss-feedly-theme#94]
Under specific circumstances the last three characters of the title are cut off (replaced with ellipsis) for no apparent reason. Other titles are longer and there's enough space, it's consistently the last three characters regardless title length.

Requirements:
 - Viewed in [horizontal split](https://camo.githubusercontent.com/663d8afcab8585a41b2a2824571c58591034a54bd3d4f33a8ed5ffb799a8aa2a/68747470733a2f2f7261772e6769746875622e636f6d2f6c657669746f2f74742d7273732d666565646c792d7468656d652f6d61737465722f73637265656e73686f74732f666565646c792d747261646974696f6e616c2e706e673f313930313131) view
 - Option "Show content preview in headlines" is disabled
 - Article has no authors
 - Using Safari (14.1 (16611.1.21.161.3) macOS)

Sanity check:
 - This is not the case with the default tt-rss theme
 - Does not happen in Firefox nor Chrome
 - Running latest versions of TT-RSS and this theme

Appears to be caused by (or rather disabling this fixes it but causes other alignement issues):
```
#content-wrap#content-wrap .hl>* {
🔶 display: flex;
  align-items: center;
  align-self: stretch
}
```

**Comment by levito** [comment]
Hi @Unending, thanks for reporting this. I can reproduce it, but I have to tell you that apparantly Safari is not supported by tt-rss anymore. When using the current tt-rss master, it won't work without reverting [this commit](https://git.tt-rss.org/fox/tt-rss/commit/143617afb1cf5f0c1fb5baa3e629b3bc92064eae).

Also, this issue only affects Safari using the settings you described, and it's a very minor issue which does not impair the UX that much. I don't see an easy fix, that's why I'd rather just close this – I hope you don't mind.

Cheers!

**Comment by Unending** [comment]
That's unfortunate @levito. I realize it's an edge case, but hey, no harm in asking.

Just for the record, TT-RSS has been working fine in Safari for the past two months since that commit. You just have to enable the requestsIdleCallback feature in the developer/advanced menu (possible on both macOS and iOS).

Thanks for all the work on this theme.
